### PR TITLE
add test which replaces an alternative group with a symlink

### PR DESCRIPTION
**Pull request by jnbr**
This bug was triggered by removing the cc alternative group from gcc and clang.
I forgot to this variant with the latest xbps.

### CODE REVIEW

**Comment by xtraeme** [comment]
right, this fails currently... do you have a fix?

**Comment by jnbr** [comment]
no, not yet

**Comment by Duncaen** [comment]
We worked around this with https://github.com/void-linux/xbps/commit/98e09e01e1d254347ab579ba849aefcb640ff8f1 for normal files and directories.

I think the only proper fix is to use the transactional files stuff, because even if we would change to updates alternatives before unpacking a package, it would still fail if the alternative was removed and moved to another package which was previously unpacked in the transaction.

**Comment by xtraeme** [comment]
FTR I just fixed this one with https://github.com/void-linux/xbps/commit/732a0e6bdf6a59e761d72fda291d52038358fdfe

**Comment by jnbr** [comment]
Thanks!

**Pull request merged**
