### PR TITLE
Ignore conf repos vs repository

### PR DESCRIPTION
**Pull request by xtraeme**
This fixes https://github.com/void-linux/xbps/issues/85

### CODE REVIEW

**Comment by xtraeme** [comment]
Pong

**Comment by Duncaen** [comment]
Hm I don't get how this works it looks like `XBPS_FLAG_IGNORE_CONF_REPOS` is only used in `initend.c` while parsing the configuration files.

**Comment by xtraeme** [comment]
This is it, I didnt write a test case but disabling the flag makes storing the repo succeed.

**Comment by Duncaen** [comment]
I don't get the original issue or I can't reproduce it here:

```
xbps$ xbps-query -i --repository=~/void-packages/hostdir/binpkgs -L
   92 /home/duncan/void-packages/hostdir/binpkgs (RSA unsigned)
xbps$ xbps-query --repository=~/void-packages/hostdir/binpkgs -i -L
   92 /home/duncan/void-packages/hostdir/binpkgs (RSA unsigned)
```

**Comment by xtraeme** [comment]
hmm right, I can't reproduce it anymore... weird.

**Pull request closed without merging**
