### PR TITLE
libxbps: remove dangling symlinks properly.

### LINKED ISSUE #23: Empty directories don't get removed on xbps-remove
When deinstalling a package, empty directories that were created by the package on installation are left behind.

For example, `cmus` leaves `/usr/lib/cmus`.
Another: `faenza-icon-theme` leaves `/usr/share/icons/Faenza*`.

It's not so that every directory is left behind, though. In the cmus example, `/usr/share/cmus` is properly cleaned up. I can't see a pattern in which case a directory is deleted and in which not.

It seems not to be package specific.

### PR DESCRIPTION
**Pull request by xtraeme**
This fixes removal of packages that contain multiple levels
of dangling symlinks, i.e faenza-icon-theme and probably others.

Close #23

### CODE REVIEW

**Comment by jnbr** [comment]
Nice!
The test looks strange to me. Shouldn't this all be `pkg_A` ?

**Comment by xtraeme** [comment]
I think it didn't matter, the key is to have some dangling symlinks. Will
review it later.

Thanks

**Comment by xtraeme** [comment]
Yeah, just checked it. It does not matter, the test is fine.

**Comment by xtraeme** [comment]
ping?

**Comment by jnbr** [comment]
>  the key is to have some dangling symlinks

I don't think you get dangling symlinks this way. 
You need a non existent target for a dangling symlink but the path of the linkname should exist which isn't the case when using `pkg_B` in this test:

```
$ mkdir -p pkg_A/usr/lib
$ touch -f pkg_A/usr/lib/libfoo.so.1.2.0
$ ln -sf libfoo.so.2 pkg_A/usr/lib/libfoo.so.1
$ tree
.
└── pkg_A
    └── usr
        └── lib
            ├── libfoo.so.1 -> libfoo.so.2
            └── libfoo.so.1.2.0

3 directories, 2 files
$ ln -sf libfoo.so.2 pkg_B/usr/lib/libfoo.so
ln: failed to create symbolic link 'pkg_B/usr/lib/libfoo.so': No such file or directory
$ tree
.
└── pkg_A
    └── usr
        └── lib
            ├── libfoo.so.1 -> libfoo.so.2
            └── libfoo.so.1.2.0

3 directories, 2 files
```

**Comment by xtraeme** [comment]
@jnbr you were right, I changed it to pkg_A, as expected.

**Comment by xtraeme** [comment]
This PR is ready for a long while... real case: fixes complete removal of faenza-icon-theme and probably others containing multiple levels of symlinks.

Would be nice if it's applied...

**Pull request merged**
