### PR TITLE
lib/util.c: verify revision in xbps_pkg_{version,revision,name}

### PR DESCRIPTION
**Pull request by Chocimier**
Fixes case of perl-PerlIO-utf8_strict: void-linux/void-packages#14005.

### CODE REVIEW

**Comment by xtraeme** [comment]
I mean, add new test cases to verify that void-linux/void-packages#14005 works correctly.

**Comment by xtraeme** [comment]
@Duncaen common/shlibs needs to be fixed

**Comment by Duncaen** [comment]
```
void-packages$ xbps-query -R --regex -p run_depends -s '_[0-9]+_[0-9]+'
FreeRADIUS-3.0.17_4: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
aide-0.16.2_1: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
audacious-plugins-3.10.1_4: libmpg123>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current)
baresip-0.6.4_1: libmpg123>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current)
btrfs-progs-5.2.2_1: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
c-client-2007f_3: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
cantata-2.3.3_1: libmpg123>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current)
cyrus-sasl-modules-2.1.27_2: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
cyrus-sasl-modules-gssapi-2.1.27_2: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
cyrus-sasl-modules-ldap-2.1.27_2: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
cyrus-sasl-modules-sql-2.1.27_2: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
deadbeef-1.8.2_1: libmpg123>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current)
e2tools-0.0.16_1: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
easyrpg-player-0.6.0_1: libmpg123>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current)
ext4magic-0.3.2_3: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
extundelete-0.2.4_4: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
fsarchiver-0.8.5_1: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
gosu-0.14.5_1: libmpg123>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current)
gst-plugins-good1-1.16.1_1: libmpg123>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current)
idjc-0.8.17_2: libmpg123>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current)
libgsasl-1.8.0_11: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
libsmbclient-3.6.25_14: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
lighttpd-1.4.54_2: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
love-11.2_1: libmpg123>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current)
mit-krb5-1.17_3: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
mit-krb5-client-1.17_3: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
mit-krb5-libs-1.17_3: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
mp3gain-1.6.2_1: libmpg123>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current)
mpd-0.21.16_1: libmpg123>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current)
mplayer-1.4_3: libmpg123>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current)
nfs-utils-2.3.3_2: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
partclone-0.3.12_3: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
qt5-fsarchiver-0.8.5_1: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
quota-4.05_1: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
reiserfsprogs-3.6.27_1: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
samba-3.6.25_14: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
smbclient-3.6.25_14: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
supermin-5.1.20_3: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
testdisk-7.1_1: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
xen-4.10.4_2: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
zerofree-1.1.1_1: e2fsprogs-libs>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current)
FreeRADIUS-32bit-3.0.17_4: e2fsprogs-libs-32bit>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
audacious-plugins-32bit-3.10.1_4: libmpg123-32bit>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
baresip-32bit-0.6.4_1: libmpg123-32bit>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
c-client-32bit-2007f_3: e2fsprogs-libs-32bit>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
cyrus-sasl-modules-32bit-2.1.27_2: e2fsprogs-libs-32bit>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
cyrus-sasl-modules-gssapi-32bit-2.1.27_2: e2fsprogs-libs-32bit>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
cyrus-sasl-modules-ldap-32bit-2.1.27_2: e2fsprogs-libs-32bit>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
cyrus-sasl-modules-sql-32bit-2.1.27_2: e2fsprogs-libs-32bit>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
deadbeef-32bit-1.8.2_1: libmpg123-32bit>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
gosu-32bit-0.14.5_1: libmpg123-32bit>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
idjc-32bit-0.8.17_2: libmpg123-32bit>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
libgsasl-32bit-1.8.0_11: e2fsprogs-libs-32bit>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
libsmbclient-32bit-3.6.25_14: e2fsprogs-libs-32bit>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
libwine-32bit-4.17_1: libmpg123-32bit>=1.13.4_2_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
mit-krb5-32bit-1.17_3: e2fsprogs-libs-32bit>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
mit-krb5-libs-32bit-1.17_3: e2fsprogs-libs-32bit>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
nfs-utils-32bit-2.3.3_2: e2fsprogs-libs-32bit>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
reiserfsprogs-32bit-3.6.27_1: e2fsprogs-libs-32bit>=1.41.5_1_1 (https://alpha.de.repo.voidlinux.org/current/multilib)
```

**Comment by xtraeme** [comment]
Those pkgs should be rebuilt once shlibs is fixed.

**Comment by Chocimier** [comment]
e2fsprogs-libs>=1.41.5_1_1 is rejected by xbps_pkg_name and xbps_pkg_version even now because of greater-sign. The only use of xbps_pkg_revision is in xbps-uhelper, so it shouldn't be problem after correction of common/shlibs.

Inequalities are processed with xbps_pkgpattern_*, which check position of greater-sign only.

**Comment by Duncaen** [comment]
As I said, this broke stuff. run_depends is not the only place where "wrong" revisions show up.

**Comment by Chocimier** [comment]
You were right, there is perl-Digest-1.17_01_1 and similar in perl's provides.

**Comment by svenper** [comment]
Would replacing `strchr` with <code>str<b>r</b>chr</code> solve any problems? Create any new ones?

**Pull request merged**
