### PR TITLE
xbps.d.5: Expand ignorepkg description, fix typo.

### PR DESCRIPTION
**Pull request by flexibeast**

### CODE REVIEW

**Comment by travankor** [comment]
Any context for this change?

Also, this behaviour is the same for: `noextract`, `include`, `preserve`, `repository`, `virtualpkg`

**Comment by flexibeast** [comment]
@travankor: Someone on IRC asked how to ignore multiple packages; the existing documentation isn't clear on how to do this. Apart from the existing text for `ignorepkg`, `xbps.d(5)` currently says:

     The configuration files can set multiple keywords that are pairs of keys and values, such as `key=value`.

which is ambiguous, and can be read as suggesting that multiple values can be supplied to a single `ignorepkg` instance, which is not the case.

Perhaps instead of modifying the `ignorepkg` description specifically, there should be text in the "Description" part stating the "multiple instances allowed, but one value per instance" constraint for  `ignorepkg` and the keywords you mentioned?

**Comment by travankor** [comment]
That sounds like a good approach (rewording last paragraph in "Description").

Apparently, `/usr/share/xbps.d/xbps.conf` serves as an annotated example, but it's not 100% in sync with that latest xbps features.

**Comment by ericonr** [comment]
We could mention the `/usr/share/xbps.d/xbps.conf` file more explicitly in that man page, perhaps.

**Comment by flexibeast** [comment]
PR updated to reflect comments so far.

**Comment by flexibeast** [comment]
Ping?

**Pull request merged**
