### PR TITLE
tests/xbps/xbps-digest: create tests.

### PR DESCRIPTION
**Pull request by ericonr**
The `big_file` one takes a while, but I think it's worth having it, if we're moving to BearSSL.

### CODE REVIEW

**Comment by Duncaen** [comment]
Not a fan of the big file test, any way we could make it optional?

**Comment by ericonr** [comment]
I'm not sure, I'm mostly cargo culting the atf stuff. It takes like 8s on my PC, is that too much?

**Comment by Duncaen** [comment]
Yes, writing 2GB each testsuite run is really not that nice.

**Comment by Duncaen** [comment]
This is useless wear on disks and +8 seconds makes tests even more annoying to run.

**Comment by ericonr** [comment]
I did try it with BearSSL and it didn't blow up, so I guess I can just leave a note to make sure to test `xbps-digest` with big files once necessary for the final transition. Will remove the big file one, then.

**Comment by ericonr** [comment]
Pushed without big file.

**Comment by ericonr** [comment]
@Duncaen anything holding this one?

**Pull request merged**
