### PR TITLE
lib/verifysig.c: don't read keys from cwd

### PR DESCRIPTION
**Pull request by Chocimier**

### CODE REVIEW

**Comment by xtraeme** [comment]
Why xbps-rindex needs to know about the rootdir? imho it's not the correct way to fix this.

**Comment by Chocimier** [comment]
Apart from testing, it may not need. But reading keys from cwd by all xbps including xbps-install isn't correct way either.

**Comment by xtraeme** [comment]
Manpage needs to be updated

**Comment by Chocimier** [comment]
Already documented in xbps-rindex manpage. There is long option only.

**Comment by Duncaen** [comment]
Imho we should just revert everything for now, we can't use the repodata signing code as it is anyways.

**Comment by Chocimier** [comment]
> Imho we should just revert everything for now, we can't use the repodata signing code as it is anyways.

Fine for me.

**Comment by xtraeme** [comment]
shall we revert the repodata signing stuff? I don't really like the fact that xbps-rindex now needs to know about rootdir, which to me is wrong.

**Comment by xtraeme** [comment]
the repodata signing patchset has been reverted, feel free to submit again.

**Pull request closed without merging**
