### PR TITLE
xbps-install -R docs fixed

### PR DESCRIPTION
**Pull request by roman-neuhauser**
* man page was flat out wrong
* usage string was inconsistent with the rest

### CODE REVIEW

**Comment by xtraeme** [comment]
This is wrong, you must use `-R` (no arguments) or `--repository=arg`

**Comment by roman-neuhauser** [comment]
> This is wrong, you must use `-R` (no arguments) or `--repository=arg`

xbps-install's behavior does not support your assertion:

```
% xbps-install -R foo | head -1
Usage: xbps-install [OPTIONS] [PKGNAME...]
```

```
% xbps-install --debug -R foo bar 2>&1 | grep foo
[DEBUG] Repository[0]=foo
[DEBUG] [rpool] checking `foo' at index 0
[DEBUG] [repo] `foo/x86_64-repodata' open repodata No such file or directory
[DEBUG] [repo] `foo' removed
```

* `-R` and `--repository` are defined as one: https://github.com/void-linux/xbps/blob/77c72f9c2c8ffbdf0839288a10a2dcebc48df36e/bin/xbps-install/main.c#L112
* and documented as such in the usage string: https://github.com/void-linux/xbps/blob/77c72f9c2c8ffbdf0839288a10a2dcebc48df36e/bin/xbps-install/main.c#L60

**Comment by xtraeme** [comment]
On glibc right?

**Comment by roman-neuhauser** [comment]
yes

**Comment by roman-neuhauser** [comment]
i should add that i don't understand how glibc vs musl would play a role here.  what would "Enable repository mode. This mode explicitly looks in repositories, rather than looking in the target root directory." even mean in `xbps-install`?  can you give me an example?

**Comment by xtraeme** [comment]
`-R foo` or `--repository foo` does not work with musl.

The only way that makes them both work is using `--repository=foo`

**Comment by roman-neuhauser** [comment]
> `-R foo` or `--repository foo` does not work with musl.
> 
> The only way that makes them both work is using `--repository=foo`

voidlinux/voidlinux-musl contradicts this claim:

```
% docker run voidlinux/voidlinux-musl xbps-install --debug --repository foo bar
[DEBUG] XBPS: 0.58 API: 20200118 GIT: UNSET
[DEBUG] Processing configuration directory: /etc/xbps.d
[DEBUG] Processing system configuration directory: /usr/share/xbps.d
[DEBUG] Parsing configuration file: /usr/share/xbps.d/00-repository-main.conf
[DEBUG] [repo] `https://alpha.de.repo.voidlinux.org/current/musl' stored successfully
[DEBUG] /usr/share/xbps.d/00-repository-main.conf: added repository https://alpha.de.repo.voidlinux.org/current/musl
[DEBUG] Parsing configuration file: /usr/share/xbps.d/musl-arch.conf
[DEBUG] /usr/share/xbps.d/musl-arch.conf: native architecture set to x86_64-musl
[DEBUG] Parsing configuration file: /usr/share/xbps.d/xbps.conf
[DEBUG] rootdir=/
[DEBUG] metadir=//var/db/xbps
[DEBUG] cachedir=/var/cache/xbps
[DEBUG] confdir=/etc/xbps.d
[DEBUG] sysconfdir=/usr/share/xbps.d
[DEBUG] syslog=true
[DEBUG] bestmatching=false
[DEBUG] Architecture: x86_64-musl
[DEBUG] Target Architecture: (null)
[DEBUG] Repository[0]=foo
[DEBUG] Repository[1]=https://alpha.de.repo.voidlinux.org/current/musl
[DEBUG] [pkgdb] added vpkg awk-0_1 for gawk
[DEBUG] [pkgdb] added vpkg openssl-3.0.2_2 for libressl
[DEBUG] [pkgdb] added vpkg eject-2.35.1_1 for util-linux
[DEBUG] [pkgdb] added vpkg rfkill-2.35.1_1 for util-linux
[DEBUG] [pkgdb] initialized ok.
[DEBUG] [rpool] checking `foo' at index 0
[DEBUG] [repo] `foo/x86_64-musl-repodata' open repodata No such file or directory
[DEBUG] [repo] `foo' removed
[DEBUG] [rpool] checking `https://alpha.de.repo.voidlinux.org/current/musl' at index 0
[DEBUG] [repo] `//var/db/xbps/https___alpha_de_repo_voidlinux_org_current_musl/x86_64-musl-repodata' open repodata No such file or directory
[DEBUG] [repo] `https://alpha.de.repo.voidlinux.org/current/musl' removed
[DEBUG] xbps_autoupdate: trans_find_pkg xbps: 2
[DEBUG] xbps_transaction_install_pkg: trans_find_pkg bar: 2
Package 'bar' not found in repository pool.
[DEBUG] xbps_pkgdb_unlock: pkgdb_fd 3
[DEBUG] [pkgdb] released ok.
```

but what does anything of this have to do with the facts that

* manual text for `xbps-install -R` describes `xbps-query -R` instead
* `--repository=repo` with the equals sign is simply a stylistic inconsistency in usage strings and man pages, and other argument-taking options are documented using the `--option arg` style

**Comment by xtraeme** [comment]
The difference between `-R, --repository` is that it takes and *optional argument*, unlike other options, so that its argument is not handled like the other ones.

**Comment by xtraeme** [comment]
oh wait, `xbps-install` uses `required_argument`. I confused it with `xbps-query`.

**Comment by xtraeme** [comment]
Your changes are ok, sorry for the confusion.

**Pull request merged**
