### PR TITLE
xbps_get_pkg_fulldeptree: switch to uthash.

### PR DESCRIPTION
**Pull request by xtraeme**
There are still two users that can benefit from
uthash: transaction_files.c and xbps-fbulk.

cc @duncaen

### CODE REVIEW

**Comment by Duncaen** [comment]
Looks good.

* Maybe we can change the api so malloc/calloc errors could be handled?
* Maybe add a internal structure that holds the hash head and the results array so that if we ever want to get full dep trees multi threaded we don't run into issues, would this make sense?

**Comment by xtraeme** [comment]
@Duncaen 

- uthash just calls exit(-1) if malloc fails
- not sure if we ever run fulldeptree multithreaded

**Comment by Duncaen** [comment]
Ok.

>     * uthash just calls exit(-1) if malloc fails

Hm I think we might have to add our own handler if we use uthash somewhere inside the transaction to at least try to recover from it, for now this looks ok.

**Comment by xtraeme** [comment]
@Duncaen I agree, I thought about this. If in the future we need this, we could set uthash hooks for malloc/free.

**Comment by xtraeme** [comment]
@Duncaen been thinking about this... we could get rid of the transaction dictionary and use a hash table with something like:

```
struct pkg {
   xbps_dictionary_t d;
   const char *pkgver;
   UT_hash_handle hh;
}
```

**Comment by Duncaen** [comment]
Yes I would like to do that, I've been playing around with that a bit.

[types.txt](https://github.com/void-linux/xbps/files/4192864/types.txt)

**Pull request closed without merging**
